recipebook/ledger/urls.py
from django.urls import path
from .views import RecipeListView, RecipeDetailView


urlpatterns = [
    path('recipes/list', RecipeListView.as_view(), name='recipe-list'),
    path('recipe/<int:pk>', RecipeDetailView.as_view(), name='recipe_detail'),
]


app_name = "ledger"

recipebook/recipebook/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ledger.urls', namespace="ledger")),
    path('accounts/', include('django.contrib.auth.urls')),
]

recipebook/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    bio = models.TextField(validators=[MinLengthValidator(255)])

    def __str__(self):
        return self.user.username

recipebook/ledger/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from accounts.models import Profile


class Ingredient(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)    
    

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('ledger:recipe_detail', args=[str(self.id)])
    

class RecipeIngredient(models.Model):
    quantity = models.CharField(max_length=100)
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE, related_name='recipe')
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')

    def __str__(self):
        return f'{self.quantity} of {self.ingredient.name}'

recipebook/accounts/views.py
from django.shortcuts import render

# Create your views here.

recipebook/ledger/views.py
from django.shortcuts import render
from .models import Recipe
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required


class RecipeListView(ListView):
    model = Recipe
    template_name = "ledger/recipe_list.html"


class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "ledger/recipe_detail.html"
    login_url = '/accounts/login/'

recipebook/ledger/templates/ledger/header.html
<header>
    {% if request.path == '/accounts/login/' %}
        <h1>Recipe Book</h1>
    {% else %}
        <h1>Recipe Book</h1>
        {% if user.is_authenticated %}
            <p>Hello, {{ user.username }}!</p>
            <form action="{% url 'logout' %}" method="POST">
                {% csrf_token %}
                <button type="submit">Logout</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    {% endif %}
</header>

recipebook/ledger/templates/ledger/recipe_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ recipe.name }}</title>
</head>
<body>
    {% include 'ledger/header.html' %}
    <h2>{{ recipe.name }}</h2>
    <p>Created on: {{ object.created_on }}<br> Updated on: {{ object.updated_on}}</p>
    <p>Author: {{ recipe.author.user.username }}</p>
    <ul>
    {% for recipe_ingredient in object.ingredients.all %}
        <li>{{ recipe_ingredient.ingredient.name }}: {{ recipe_ingredient.quantity }}</li>
    {% endfor %}
    </ul>
    <a href="{% url 'ledger:recipe-list' %}">Back to list</a>
</body>
</html>

recipebook/ledger/templates/ledger/recipe_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Recipe List</title>
</head>
<body>
    {% include 'ledger/header.html' %}
    <h2>Recipe List</h2>
    <ul>
    {% for recipe in object_list %}
        <li><a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a></li>
    {% endfor %}
    </ul>
</body>
</html>